name: 构建和测试 Chrome 扩展

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 运行构建脚本
        run: npm run build-no-zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: 'hpms-tool-*.zip'

  lint:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 检查 package.json 格式
        run: |
          if ! npx jsonlint package.json; then
            echo "package.json 格式不正确"
            exit 1
          fi

      - name: 检查 manifest.json 格式
        run: |
          if ! npx jsonlint src/manifest.json; then
            echo "manifest.json 格式不正确"
            exit 1
          fi